use_frameworks!

target 'EmojiLog_Example' do
  pod 'EmojiLog', :path => '../'

  target 'EmojiLog_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.9.3'
  pod 'Nimble', '~> 4.1.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
